---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: "{{ .Release.Name }}-metrics-service"
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    control-plane: controller-manager

